name: Sync Pull Request

on:
  schedule:
    - cron: "0 0 * * *" # This runs the action every day at midnight (UTC)
  workflow_dispatch:

jobs:
  sync_pull_request:
    name: Sync Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git committer identity
        run: |
          git config --global user.name "Sync Pull Request Action"
          git config --global user.email \<\>
          git checkout main
          git pull

      - name: Check if sync_pull_request branch exists
        id: check_branch
        run: |
          if git show-ref --quiet refs/heads/sync_pull_request; then
            echo "sync_pull_request branch exists"
            git branch -D sync_pull_request
          else
            echo "sync_pull_request branch does not exist"
          fi
        continue-on-error: true
        shell: bash

      - name: Merge upstream/master into sync_pull_request
        uses: discdiver/merge-from-upstream-repo@v0.0.9
        with:
          upstream: Notsfsssf/pixez-flutter
          upstream-branch: master
          branch: sync_pull_request
          useremail: \<\>
          username: Sync Pull Request Action

      - name: Check for changes between branches
        id: check_changes
        run: |
          changes=$(git diff main sync_pull_request)
          if [ -z "$changes" ]; then
            echo "No new changes found. Exiting..."
            exit 1
          fi
        shell: bash

      - name: Push changes to the new branch
        run: |
          git push origin sync_pull_request

      - name: Check existing pull requests
        id: check_pr
        run: |
          pr=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?head=your_username:sync_pull_request" | jq -r '.[0].state')
          echo "pull_request_state=$pr" >> $GITHUB_ENV
        shell: bash

      - name: Create pull request if not exists or closed
        if: env.pull_request_state == 'closed' || env.pull_request_state == 'null'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge changes from upstream"
          title: "Sync Pull Request - YYYY-MM-DD" # Replace with a custom title
          body: "This pull request was automatically generated by a daily GitHub Action to merge changes from upstream."
          branch: "sync_pull_request"
          base: "main"
