name: Sync Main

on:
  schedule:
    - cron: "0 0 * * *" # This runs the action every day at midnight (UTC)
  workflow_dispatch:

jobs:
  sync_pull_request:
    name: Sync Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge upstream/master into main
        uses: exions/merge-upstream@v1
        with:
          upstream: Notsfsssf/pixez-flutter
          upstream-branch: master
          branch: main
