name: Sync Pull Request

on:
  schedule:
    - cron: "0 0 * * *" # This runs the action every day at midnight (UTC)
  workflow_dispatch:

jobs:
  daily_pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a new branch and pull changes from upstream
        run: |
          git checkout -b sync_pull_request
          git remote add upstream https://github.com/Notsfsssf/pixez-flutter.git
          git fetch upstream
          git merge upstream/main

      - name: Push changes to the new branch
        run: |
          git push origin sync_pull_request

      - name: Check existing pull requests
        id: check_pr
        run: |
          pr=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?head=getBoolean:sync_pull_request" | jq -r '.[0].state')
          echo "::set-output name=pull_request_state::$pr"
        shell: bash

      - name: Create pull request if not exists or closed
        if: steps.check_pr.outputs.pull_request_state == 'closed' || steps.check_pr.outputs.pull_request_state == 'null'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge changes from upstream"
          title: "Sync Pull Request - YYYY-MM-DD" # Replace with a custom title
          body: "This pull request was automatically generated by a daily GitHub Action to merge changes from upstream."
          branch: "sync_pull_request"
          base: "main"
